config/routes.rb
Rails.application.routes.draw do
 devise_for :users , controllers:{ sessions: "users/sessions" , :registrations => "users/registrations"}
 root to:"home#index"
 resource :users
 resource :adminparams
 resources :courses do
 resources :feedbacks, :controller => 'course_feedbacks'
 end
 
 resources :courses do
  	resources :pastexams, :controller => 'course_pastexams'
 end
 resources :camp_activities do
 	resources :camp_practices  , :controller => 'activity_practices'
 end
 resources :camp_workers
 match "/uploads/pastexam", :controller => "course_pastexams", :action => "block", :via => :all
 match ':controller(/:action(/:id(.:format)))', :via => :all
 
 get "/uploads/:id", :controller => "course_pastexams", :action => "download"
 
 
get "users/hero" 
 
 

end

app/controllers/activity_practices_controller.rb
class ActivityPracticesController < ApplicationController
	before_action :find_activity 

	def index
		@camp_practices = @camp_activity.camp_practices 
	end 
	def show 
		@camp_practice = @camp_activity.camp_practices.find(params[:id])
	end
	def new 
		@camp_practice = @camp_activity.camp_practices.build 
	end
	def create
		@camp_practice = @camp_activity.camp_practices.build(practice_params)
		if @camp_practice.save
			redirect_to camp_activity_camp_practices_url (@camp_activity)
		else
			render :action => :new 
		end
	end
	def edit 
		@camp_practice = @camp_activity.camp_practices.find(params[:id])
	end
	def update
		@camp_practice = @camp_activity.camp_practices.find(params[:id])
		if @camp_practice.update(practice_params)
			redirect_to camp_activity_camp_practices_url (@camp_activity)
		else
			render :action => :edit
		end
	end
	def destroy 
		@camp_practice = @camp_activity.camp_practices.find(params[:id])
		@camp_practice.destroy 
		redirect_to camp_activity_camp_practices_url(@camp_activity)
	end
protected 
	def find_activity
		@camp_activity = CampActivity.find( params[:camp_activity_id])
	end
	def practice_params
		params.require(:camp_practice).permit(:name , :starts_at)
	end
end

app/helpers/activity_practices_helper.rb
module ActivityPracticesHelper
end

app/views/activity_practices/edit.html.erb
<%= form_for @camp_practice , :url => camp_activity_camp_practice_path(@camp_activity , @camp_practice) , :html => {:method => :patch} do |f|%>
	<ul>
		<li>
			<%= f.label :name , "Purpose" %>
			<%= f.text_field :name%>
		</li>	
		
		<li>	
		<%= f.label :starts_at, "Time" %>
   	<%= f.datetime_select :starts_at %>
	 	</li>
	</ul>
	<p>	<%= f.submit "Update"%></p>
												

<% end%>

app/views/activity_practices/index.html.erb
<ul>
	<% @camp_practices.each do |p| %>
	<li>
					  <%= p.name %>
					  <%= link_to 'show', camp_activity_camp_practice_path(@camp_activity, p) %>
					  <%= link_to 'edit', edit_camp_activity_camp_practice_path(@camp_activity, p) %>
						<%= link_to 'destroy', camp_activity_camp_practice_path(@camp_activity, p) , :method => :delete %>
	</li>
	<% end %>

</ul>
		<%= link_to 'new practice', new_camp_activity_camp_practice_path(@camp_activity) %>

app/views/activity_practices/new.html.erb
<%= form_for @camp_practice  , :url => camp_activity_camp_practices_path(@camp_activity) do |f|%>
	<ul>
		<li>
			<%= f.label :name , "Purpose" %>
			<%= f.text_field :name%>
		</li>	
		
		<li>	
		<%= f.label :starts_at, "Time" %>
   	<%= f.datetime_select :starts_at %>
	 	</li>
	</ul>
	<p>	<%= f.submit "Create"%></p>
												

<% end%>

app/views/activity_practices/show.html.erb
<ul>
	<li> <%= @camp_practice.name %></li>
	<li> <%= @camp_practice.starts_at %></li>
</ul>