config/routes.rb
Rails.application.routes.draw do
 devise_for :users , controllers:{ sessions: "users/sessions" , :registrations => "users/registrations"}
 root to:"home#index"
 resource :users
 resource :adminparams
 resources :courses do
 resources :feedbacks, :controller => 'course_feedbacks'
 end
 
 resources :courses do
  	resources :pastexams, :controller => 'course_pastexams'
 end
 resources :camp_activities do
 	resources :camp_practices  , :controller => 'activity_practices'
 end
 resources :camp_workers
 match "/uploads/pastexam", :controller => "course_pastexams", :action => "block", :via => :all
 match ':controller(/:action(/:id(.:format)))', :via => :all
 
 get "/uploads/:id", :controller => "course_pastexams", :action => "download"
 
 
get "users/hero" 
 
 

end

app/controllers/course_pastexams_controller.rb
class CoursePastexamsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_course,:except => [:download]
  before_action :find_adminparam  
  before_action :user_confirm, :except => [:download]

  def index
    @type_list= ["Midterm","Final","Quiz","Homework","Project","others"]
    @pastexams = @course.pastexams.order("year").page(params[:page]).per(10)
    
  end
  
  def show
    @pastexam = @course.pastexams.find(params[:id])
  end

  def new
    @pastexam = @course.pastexams.build
  end

  def create
    @pastexam = @course.pastexams.build( pastexam_params )
    @pastexam.user_id = current_user.id
    @pastexam.point_get = @adminparam.point_get_pastexam
    if @pastexam.save
      redirect_to course_pastexams_url( @course )
      current_user.rank+=@adminparam.point_get_pastexam
      current_user.maxrank+=@adminparam.point_get_pastexam
      current_user.save
    else
      render :action => :new
    end
  end

  def edit
    @pastexam = @course.pastexams.find(params[:id])
  end

  def update
  @pastexam = @course.pastexams.find( params[:id] )

  if @pastexam.update( pastexam_params )
    redirect_to course_pastexams_url( @course )
  else
    render :action => :edit
  end

  end

  def destroy
    @pastexam = @course.pastexams.find( params[:id] )
    if @pastexam.user != current_user
      @pastexam.user.rank-=@adminparam.point_get_pastexam
      @pastexam.user.save
    else
      if @pastexam.point_get
        current_user.rank-=@pastexam.point_get
        current_user.maxrank-=@pastexam.point_get
        current_user.save
      end
    end
    path = getfilename(@pastexam,@course)
    if File.exist? path
    	FileUtils.rm(path)
    end
    @pastexam.destroy

    redirect_to course_pastexams_url( @course )
  end

  def download
    @pastexam = Pastexam.find( params[:id] )
    
    @course = @pastexam.course
    if current_user.rank < @adminparam.point_need_pastexam
        flash[:alert] = t("Points not enough")
	redirect_to course_pastexams_path(@course)
    else
	new_point = @pastexam.download_time+=1
        #@pastexam.save
	path = getfilename(@pastexam,@course)
	send_file path, :x_sendfile=>true
	current_user.rank -= @adminparam.point_need_pastexam
	current_user.save
	#@pastexam.update(:download_time => new_point)
    end
  end

  def block
    redirect_to root_url
  end

  protected

  def find_course
    @course = Course.find( params[:course_id] )
  end
   
  def find_adminparam
    @adminparam = Adminparam.first
  end

  def pastexam_params
	params.require(:pastexam).permit(:file ,:exam_type, :has_answer, :year,:which_time,:description)
  end

  def getfilename(pastexam,course)
    truename = ""
    filename = pastexam.file.url.split("/").last.split(".").first 
    l = pastexam.file.url.split(".").length
    if l == 1
      truename = filename + "#{pastexam.id}"
    else
      truename = filename +"#{pastexam.id}." + pastexam.file.url.split(".").last
    end
    year_list= ["","freshman","sophomore","juniorandsenior","graduate","language","general"]
    type_list= ["mid","final","quiz","hw","prj","others"]
    path = "#{Rails.root}/pastexam/#{year_list[course.grade]}/#{course.name}/#{course.instructor}/#{truename}"
    return path
  end

  def user_confirm
     @course = Course.find(params[:course_id])
     if current_user.is_admin < 0
         flash[:alert] = t("Your account has not been approved by the administrator")
         redirect_to course_url(@course)
     end
       
  end

end

app/helpers/course_pastexams_helper.rb
module CoursePastexamsHelper
end

app/views/course_pastexams/index.html.erb
<p>
<%= link_to t('Back to Home'), root_url, :class => "btn btn-info" %>
<%= link_to t('Back to Course Index'), courses_path, :class => "btn btn-info" %>
<%= link_to t('Back to Course'), course_path(@course), :class => "btn btn-info", :method => :get%>

<h1><%= @course.name %> <%= @course.instructor %></h1>


<table width="1" style="word-break:break-all" class="table table-hover">
  <tr>
    <th><%= t('Year') %></th>
    <th><%= t('Uploader') %></th>
    <th><%= t('Answer') %></th>
    <th><%= t('Type') %></th>
    <th><%= t('Link') %></th>
    <th><%= t('Publish date') %></th>
    <th><%= t('Description') %></th>
    <th><%= t('Delete') %>
</th>
  </tr>
  
  <% @pastexams.each do |pastexam| %>
  
	<tr>
	  <td><%= pastexam.year %></td>
	  <td>
          <%= link_to "#{pastexam.user.nick_name}", :controller => 'users', :action => 'show',:id => pastexam.user %></td>
          <% if pastexam.has_answer == true %>
            <td><%= t('yes') %></td>
          <% else %>
            <td><%= t('no') %></td>
          <% end %>
          <td>
          <%= t(@type_list[pastexam.exam_type]) %>
          <%= pastexam.which_time %>
          </td>
          <td><%= link_to t("Download file"), "/uploads/#{pastexam.id}" %></td>
          <td><%= pastexam.created_at.to_date %></td>
          <td><%= pastexam.description %></td>
          
          <%if pastexam.user == current_user || current_user.is_admin>0%>
            <td><%= link_to t('Delete'), course_pastexam_path(@course, pastexam),:method => :delete , data: { confirm: t('Are you sure') }%></td>
          <%else%>
          <td></td>
          <% end %>
           
        </tr>
   <% end %>
   </table>

<%= paginate @pastexams %>
<p>
<%= link_to t('New Pastexam'), new_course_pastexam_path(@course), :class => "btn btn-primary", :method => :get %>
</p>

app/views/course_pastexams/new.html.erb
<%= form_for @pastexam, :url => course_pastexams_path(@course) do |f| %>
    
    <div class = "field">
		<%= f.label :year, t('Year')%>
		<p><%= f.select (:year),	
	  	 options_for_select((1991..2031))
		%></p>
    </div>
    <div class = "field">
		<%= f.label :exam_type, t('Exam Type')%>
		<p><%= f.select (:exam_type),	
	  	 options_for_select([[t('Midterm'), 0], [t('Final'), 1], [t('Quiz'),2],[t('Homework'),3],[t('Project'),4],[t('others'),5]]) 
		%></p>
    </div>
    <div class = "field">
		<%= f.label :which_time, t('Which time')%>
		<p><%= f.select (:which_time),	
	  	 options_for_select((1..30))
		%></p>
    </div>
    <div class = "field">
		<%= f.label :has_answer, t('Has Answer')%>
		<p><%= f.select (:has_answer),	
	  	 options_for_select([[t('no'), 0], [t('yes'), 1]]) 
		%></p>
    </div>
    <p><%= f.label :file , t('File')%>
    <%= f.file_field :file %></p>
    <% if @pastexam.errors[:file].presence %>
        <%= @pastexam.errors[:file].join(", ") %>
    <% end %>
   
    <p><%= f.label :description, t("Description(max 15 words)") %></p>
    <p><%= f.text_area :description %></p>
    
    <p><%= f.submit t("Create") %></p>

<% end %>

<p><%= button_to t('Back to Pastexam Index'),{ :controller => 'course_pastexams', :action => 'index'}, :method => 'get' %></p>

app/views/course_pastexams/show.html.erb
<p> Course: <%= @course.name %> </p>
<p> Instructor: <%= @course.instructor %> </p>
<p> Year: <%= @pastexam.year %> </p>
<p> Download file: <%= link_to "Download file", "/uploads/#{@pastexam.id}" %></p>
<p> Author: <%= @pastexam.user.last_name %> <%= @pastexam.user.first_name %></p>
<%= link_to 'back to pastexam list', course_pastexams_url(@course) %>