config/routes.rb
Rails.application.routes.draw do
 devise_for :users , controllers:{ sessions: "users/sessions" , :registrations => "users/registrations"}
 root to:"home#index"
 resource :users
 resource :adminparams
 resources :courses do
 resources :feedbacks, :controller => 'course_feedbacks'
 end
 
 resources :courses do
  	resources :pastexams, :controller => 'course_pastexams'
 end
 resources :camp_activities do
 	resources :camp_practices  , :controller => 'activity_practices'
 end
 resources :camp_workers
 match "/uploads/pastexam", :controller => "course_pastexams", :action => "block", :via => :all
 match ':controller(/:action(/:id(.:format)))', :via => :all
 
 get "/uploads/:id", :controller => "course_pastexams", :action => "download"
 
 
get "users/hero" 
 
 

end

app/controllers/course_feedbacks_controller.rb
class CourseFeedbacksController < ApplicationController
  before_action :authenticate_user!
  before_action :find_course
  before_action :find_user
  before_action :find_adminparam
  before_action :user_confirm

  def index 
    @feedbacks= @course.feedbacks.order("year").page(params[:page]).per(10)
  end

  def show
    @feedback = @course.feedbacks.find(params[:id])
    @feedback.visit_time+=1
    @feedback.save
  end
  
  def new
    @feedback = @course.feedbacks.build
  end

  def create
    @feedback = @course.feedbacks.build( feedback_params )
    @feedback.user_id=@user.id 
    @feedback.point_get = @adminparam.point_get_feedback
    if @feedback.save
      redirect_to course_feedbacks_url(@course)
      @user.rank+=@adminparam.point_get_feedback
      @user.maxrank+=@adminparam.point_get_feedback
      @user.save
    else
      render :action => :new
    end 
  end

  def edit
    @feedback = @course.feedbacks.find(params[:id])
  end

  def update
    @feedback = @course.feedbacks.find(params[:id])
    if @feedback.update(feedback_params)
       redirect_to course_feedbacks_url(@course)
    else
       render :action => :edit
    end 
  end

  def destroy
    @feedback = @course.feedbacks.find(params[:id])
    
    if @feedback.user != @user
      @feedback.user.rank-=@adminparam.point_get_feedback
      @feedback.user.save
    else
      if @feedback.point_get
        @user.rank-=@feedback.point_get
        @user.maxrank-=@feedback.point_get
        @user.save
      end
    end
    @feedback.destroy
    redirect_to course_feedbacks_url(@course)
  end

  protected
  
  def find_course
    @course = Course.find(params[:course_id])
  end
   
  def find_adminparam
    @adminparam = Adminparam.first
  end
  
  def find_user
    @user = current_user
  end

  def feedback_params
    params.require(:feedback).permit(:content,:year,:rating,:lecture_way,:partitioning,:test_homework,:other)
  end
  
  def user_confirm
     @course = Course.find(params[:course_id])
     if current_user.is_admin < 0
         flash[:alert] = t("Your account has not been approved by the administrator")
         redirect_to course_url(@course)
     end
       
  end
end

app/helpers/course_feedbacks_helper.rb
module CourseFeedbacksHelper
end

app/views/course_feedbacks/edit.html.erb
<%= form_for @feedback, :url => course_feedback_path(@course,@feedback),:html => {:method => :patch} do |f| %>
    
    <div class = "field">
		<%= f.label :year, t('Year')%>
		<p><%= f.select (:year),	
	  	 options_for_select((1991..2031),@feedback.year)
		%></p>
    </div>
    <div class = "field">
		<%= f.label :rating, t('Rating')%>
		<p><%= f.select (:rating),	
	  	 options_for_select((1..10),@feedback.rating)
		%></p>
    </div>

    
    <p><%= f.label :content, t("Content") %></p>
    <p><%= f.text_area :content %></p>

    <p><%= f.label :lecture_way, t("Lecture way") %></p>
    <p><%= f.text_area :lecture_way %></p>

    <p><%= f.label :test_homework, t("Test and homework") %></p>
    <p><%= f.text_area :test_homework %></p>
    
    <p><%= f.label :partitioning, t("Partitioning") %></p>
    <p><%= f.text_area :partitioning %></p>

    <p><%= f.label :other, t("Other") %></p>
    <p><%= f.text_area :other %></p>

    <%= f.submit t("Update") %>
<% end %>

<p><%= button_to t('Back to Feedback Index'), course_feedbacks_path(@course), :method => 'get'  %></p>

app/views/course_feedbacks/index.html.erb
<p>
<%= link_to t('Back to Home'), root_url, :class => "btn btn-info" %>
<%= link_to t('Back to Course Index'), courses_path, :class => "btn btn-info" %>
<%= link_to t('Back to Course'), course_path(@course), :class => "btn btn-info", :method => :get%>
</p>

<h1><%= @course.name %> <%= @course.instructor %></h1>

<table class="table table-hover">
  <tr>
    <th><%= t('Year') %></th>
    <th><%= t('Rating') %></th>
    <th><%= t('Author') %></th>
    <th><%= t('Link') %></th>
    <th><%= t('Publish date') %></th>
    <th><%= t('View time') %></th>
    <th><%= t('Edit') %></th>
    <th><%= t('Delete') %></th>
  </tr>
<% @feedbacks.each do |feedback| %>
	  <tr>
	  <th><%= feedback.year %>   

          <th><%= feedback.rating%></th>     
  
          <th><%= link_to "#{feedback.user.nick_name}", :controller => 'users', :action => 'show',:id => feedback.user %></th>

          <% if current_user.rank >= @adminparam.point_need_feedback || current_user == feedback.user || current_user.is_admin==1 %>
	    <th><%= link_to t('show feedback'), course_feedback_path(@course, feedback) %></th>
          <%else%>
            <th><%= t('Points not enough') %></th>
          <%end%>

          <th><%= feedback.updated_at.to_date %></th>
          <th><%= feedback.visit_time %></th>
          <% if current_user == feedback.user || current_user.is_admin>0 %>
	    <th><%= link_to t('Edit'), edit_course_feedback_path(@course, feedback) %></th>
	    <th><%= link_to t('Delete'), course_feedback_path(@course, feedback),
	                              :method => :delete , data: { confirm: t('Are you sure') }%></th>
          <%else%>
            <th></th>
            <th></th>
          <% end %>
          </tr>
          
	
<% end %>
</table>
<%= paginate @feedbacks %>

<p>
<%= link_to t('New Feedback'), new_course_feedback_path(@course), :class => "btn btn-primary", :method => :get %>
</p>

app/views/course_feedbacks/new.html.erb
<%= form_for @feedback, :url => course_feedbacks_path(@course) do |f| %>
    
    <div class = "field">
		<%= f.label :year, t('Year')%>
		<p><%= f.select (:year),	
	  	 options_for_select((1991..2031))
		%></p>
    </div>
    <div class = "field">
		<%= f.label :rating, t('Rating')%>
		<p><%= f.select (:rating),	
	  	 options_for_select((1..10))
		%></p>
    </div>

    
    <p><%= f.label :content, t("Content") %></p>
    <p><%= f.text_area :content %></p>

    <p><%= f.label :lecture_way, t("Lecture way") %></p>
    <p><%= f.text_area :lecture_way %></p>

    <p><%= f.label :test_homework, t("Test and homework") %></p>
    <p><%= f.text_area :test_homework %></p>
    
    <p><%= f.label :partitioning, t("Partitioning") %></p>
    <p><%= f.text_area :partitioning %></p>

    <p><%= f.label :other, t("Other") %></p>
    <p><%= f.text_area :other %></p>
    
    <%= f.submit t("Create") %>

<% end %>

<p><%= button_to t('Back to Feedback Index'),{ :controller => 'course_feedbacks', :action => 'index'}, :method => 'get' %></p>

app/views/course_feedbacks/show.html.erb
<p>
<%= link_to t('Back to Home'), root_url, :class => "btn btn-info" %>
<%= link_to t('Back to Course Index'), courses_path, :class => "btn btn-info" %>
<%= link_to t('Back to Course'), course_path(@course), :class => "btn btn-info", :method => :get%>
<%= link_to t('Back to Feedback Index'), course_feedbacks_url(@course), :class => "btn btn-info", :method => :get %>
</p>

<table style="word-break:break-all" class="table">
<tr><th width="33%"><%= t('Course Name') %></th>            <td><%= @course.name %></td></tr>
<tr><th width="33%"><%= t('Instructor') %></th>        <td><%= @course.instructor %></td></tr>
<tr><th width="33%"><%= t('Year') %></th>              <td><%= @feedback.year %></td></tr>
<tr><th width="33%"><%= t('Content') %></th>           <td><%= simple_format(@feedback.content) %> </td></tr>
<tr><th width="33%"><%= t('Lecture way') %></th>       <td><%= simple_format(@feedback.lecture_way) %> </td></tr>
<tr><th width="33%"><%= t('Test and homework') %></th> <td><%= simple_format(@feedback.test_homework) %> </td></tr>
<tr><th width="33%"><%= t('Partitioning') %></th>      <td><%= simple_format(@feedback.partitioning) %> </td></tr>
<tr><th width="33%"><%= t('Other') %></th>             <td><%= simple_format(@feedback.other) %> </td></tr>
<tr><th width="33%"><%= t('Rating') %></th>            <td><%= @feedback.rating %> </td></tr>
<tr><th width="33%"><%= t('Author') %></th>            <td><%= @feedback.user.last_name %> <%= @feedback.user.first_name %></td></tr>
</table>