config/routes.rb
Rails.application.routes.draw do
 devise_for :users , controllers:{ sessions: "users/sessions" , :registrations => "users/registrations"}
 root to:"home#index"
 resource :users
 resource :adminparams
 resources :courses do
 resources :feedbacks, :controller => 'course_feedbacks'
 end
 
 resources :courses do
  	resources :pastexams, :controller => 'course_pastexams'
 end
 resources :camp_activities do
 	resources :camp_practices  , :controller => 'activity_practices'
 end
 resources :camp_workers
 match "/uploads/pastexam", :controller => "course_pastexams", :action => "block", :via => :all
 match ':controller(/:action(/:id(.:format)))', :via => :all
 
 get "/uploads/:id", :controller => "course_pastexams", :action => "download"
 
 
get "users/hero" 
 
 

end

app/models/adminparam.rb
class Adminparam < ActiveRecord::Base
end

app/models/camp_activity.rb
class CampActivity < ActiveRecord::Base
	has_many :camp_activity_workerships 
	has_many :camp_workers , :through => :camp_activity_workerships


	has_many :camp_practices 
end

app/models/camp_activity_workership.rb
class CampActivityWorkership < ActiveRecord::Base
	belongs_to :camp_worker
	belongs_to :camp_activity

end

app/models/camp_practice.rb
class CampPractice < ActiveRecord::Base
	belongs_to :camp_activity

end

app/models/camp_worker.rb
class CampWorker < ActiveRecord::Base
	has_many :camp_activity_workerships 
	has_many :camp_activities , :through => :camp_activity_workerships

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :feedbacks
  has_many :pastexams

  validates_presence_of :name, :description,:instructor
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
  validates_presence_of :content, :rating, :year,:partitioning,:test_homework,:lecture_way
end

app/models/pastexam.rb
class Pastexam < ActiveRecord::Base
  belongs_to :course
  belongs_to :user
  mount_uploader :file, AttachmentUploader
  validate :file_size
  validates_length_of :description, :maximum => 15
  validates_presence_of :file

  def file_size
    if file.file
      if file.file.size.to_f/(1000*1000) > 50.0
        errors.add(:file, "You cannot upload a file greater than 50 MB")
      end
    end
  end
  #validates_presence_of :year,:which_time
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :feedbacks
  has_many :pastexams
	validates_uniqueness_of :username
	validates_presence_of :username
	validates :username , length: {in: 4..20}

	attr_accessor :login
  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions.to_hash).where(["username = :value OR lower(email) = lower(:value) ", { :value => login }]).first
		else
	    where(conditions.to_hash).first
	  end
  end
  

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_course, :only => [ :show, :edit, :update, :destroy]
  before_action :set_user 
	
  def index
    @button_style = ["","btn btn-link","btn btn-link","btn btn-link","btn btn-link","btn btn-link","btn btn-link"]
    @year_list= ["","Freshman","Sophomore","Junior and Senior","Graduate","Foreign Language","General Knowledge"]
    if params[:keyword] and not params[:keyword] == ''
        @courses = Course.where( [ "name like ? OR instructor like ?", "%#{params[:keyword]}%", "%#{params[:keyword]}%" ] ).order('grade').page(params[:page]).per(1000)
	@result = "#{@courses.count} results matching keyword ' #{params[:keyword]} '"
    elsif params[:grade]
        @courses = Course.where(:grade => params[:grade]).order('name').page(params[:page]).per(10)
        @button_style[params[:grade].to_i] = "btn btn-info"
    else
        @courses = Course.where(:grade => 1).order('name').page(params[:page]).per(10)
        @button_style[1] = "btn btn-info"
    end
  end

  def new
    @course = Course.new
  end

  def create
    @course=Course.new(course_params)
    #@course.save
    
    if @course.save
      redirect_to courses_url
    else
      render :action => :new
    end
    
    #redirect_to courses_url
  end
  
  def show
    #@course = Course.find(params[:id])
    grade_selector=['','Freshman','Sophomore','Junior and Senior','Graduate','Foreign Language','General Knowledge']
    @average_rate = 0
    if not @course.feedbacks.count == 0 
        @average_rate = @course.feedbacks.average(:rating)
    end
    @grade = grade_selector[@course.grade]
  end
  
  def destroy
    #@course = Course.find(params[:id])
    @course.destroy

    redirect_to courses_url
  end

  def edit
    #@course = Course.find(params[:id])
  end
  
  def update
    #@course = Course.find(params[:id])
    #@course.update(course_params)
    
    if @course.update(course_params)
      redirect_to courses_url(@course)
    else
      render :action => :edit
    end
   
    #redirect_to courses_url(@course)
  end
  
  private

  def course_params
    params.require(:course).permit(:name, :instructor, :grade, :description)
  end

  def set_course
    @course = Course.find(params[:id])
  end
  def set_user
    @user = current_user 
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
#	before_action :authenticate_user!
	def index
		if	user_signed_in?
			@user = current_user
		end
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!

	def index
		@users = User.where([ "is_admin <= ?", 1])
	end
	def show
	 if params[:id]
	   @user= User.find(params[:id])
         end
	end

 	def hero
          if params[:keyword]
            @users = User.where([ "is_admin <= ?", 1]).where( [ "first_name like ? OR nick_name like ? OR last_name like ? OR class_year like ?", "%#{params[:keyword]}%", "%#{params[:keyword]}%","%#{params[:keyword]}%","%#{params[:keyword]}%" ] ).page(params[:page]).per(10)
          else
            @users = User.where([ "is_admin <= ?", 1]).order('maxrank DESC').page(params[:page]).per(10)
          end
	end

        def assign
           @user = User.find(params[:id])
           @user.is_admin = 1
           @user.save
           redirect_to :action => :show, :id => @user.id
        end
        
        def unassign
   	   @user = User.find(params[:id])
           @user.is_admin = 0
           @user.save
           redirect_to :action => :show, :id => @user.id
        end
  
        def confirm
           @user = User.find(params[:id])
           @user.is_admin = 0
           @user.save
           redirect_to :action => :hero
        end

        def add_point
           @user = User.find(params[:id])
           @user.rank += params[:add_point].to_i
           @user.maxrank += params[:add_point].to_i
           @user.save
           redirect_to :action => :show, :id => @user.id
        end
  

end

app/helpers/adminparam_helper.rb
module AdminparamHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/camp_activities_helper.rb
module CampActivitiesHelper
end

app/helpers/camp_workers_helper.rb
module CampWorkersHelper
	
	def get_department_name(n)
		if n == 1
			return "行政"
		elsif n == 2
			return "活動"
		elsif n == 3
			return "生活"
		elsif n == 4
			return "場器"
		elsif n == 5
			return "美宣"
		elsif n == 6
			return "公關"
		elsif n == 7
			return "課程"
		else 
			return "其他"
	
		end
	
	end


end

app/helpers/course_feedbacks_helper.rb
module CourseFeedbacksHelper
end

app/helpers/course_pastexams_helper.rb
module CoursePastexamsHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/edit.html.erb
<%= form_for @course, :url => course_path(@course), :method => :patch do |f| %>
    <p><%= f.label :name, t("Course Name") %></p>
    <p><%= f.text_field :name %></p>

    <p><%= f.label :instructor, t("Instructor") %></p>
    <p><%= f.text_field :instructor %></p>

    <div class = "field">
	<%= f.label :grade, t("Grade")%>
	<p><%= f.select (:grade),	
	  	 options_for_select({t('Freshman')=> 1,t('Sophomore')=> 2,t('Junior and Senior')=> 3,t('Graduate')=> 4,t('Foreign Language') => 5,t('General Knowledge') => 6} ,@course.grade)
		%></p>
    </div>

    <p><%= f.label :description, t("Description") %></p>
    <p><%= f.text_area :description %></p>

    <%= f.submit t("Update") %>
<% end %>

<p><%= button_to t('Back to Course Index'),{ :controller => 'courses', :action => 'index'}, :method => 'get' %></p>

app/views/courses/index.html.erb
<p>
  <%= link_to t('Back to Home'), root_url, :class => "btn btn-info", :method => :get %>
</p>

<p>
  <%= link_to t('New Course'), new_course_path, :class => "btn btn-primary"%>
</p>

<p>
<%= form_tag courses_path, :method => :get do %>
  <%= text_field_tag "keyword" %>
  <%= submit_tag t("Search instructor or course name") %>
<% if @result %>
<%= @result %>
<%end%>
<% end %>

</p>

<p>
  <%= link_to t('Freshman'), {:controller=> 'courses', :action => 'index', :grade => 1}, :class => @button_style[1], :style => 'width: 16%' %>
  <%= link_to t('Sophomore'), {:controller=> 'courses', :action => 'index', :grade => 2}, :class => @button_style[2], :style => 'width: 16.66%' %>
  <%= link_to t('Junior and Senior'), {:controller=> 'courses', :action => 'index', :grade => 3}, :class => @button_style[3], :style => 'width: 16%' %>
  <%= link_to t('Graduate'), {:controller=> 'courses', :action => 'index', :grade => 4}, :class => @button_style[4], :style => 'width: 16%' %>
  <%= link_to t('Foreign Language'), {:controller=> 'courses', :action => 'index', :grade => 5}, :class => @button_style[5], :style => 'width: 16%' %>
  <%= link_to t('General Knowledge'), {:controller=> 'courses', :action => 'index', :grade => 6}, :class => @button_style[6], :style => 'width: 16%'%>
</p>

<ul>
<table class="table table-hover">
  <tr>  
    <th><%= t("Grade") %></th>
    <th><%= t("Course Name") %></th>
    <th><%= t("Instructor") %></th>

    <th><%= t("Feedbacks") %></th>
    <th><%= t("Pastexams") %></th>
    <%if current_user.is_admin >0%>
      <th><%= t("Edit") %></th>
      <th><%= t("Delete") %></th>
    <%end%>
  </tr>
<% @courses.each do |course| %>
  <tr>
    <td><%= t(@year_list[course.grade]) %></td>
    <td><%=link_to "#{course.name}" , course_path(course)%></td> 
    <td><%=course.instructor%></td>
    
    <td><%= course.feedbacks.count %> </td>
    <td><%= course.pastexams.count %> </td>
    <% if @user.is_admin  > 0  %>
      <th><%= link_to t('Edit'), edit_course_path(course)%></th>
      <th><%= link_to t('Delete'),course_path(course), :method => :delete, data: { confirm: t('Are you sure') } %></th>
    <%end %>
  </tr>
<% end %>
</table>
<%= paginate @courses %>
</ul>

app/views/courses/new.html.erb
<%= form_for @course, :url => courses_path do |f| %>
    <p><%= f.label :name, t("Course Name") %></p>
    <p><%= f.text_field :name %></p>

    <p><%= f.label :instructor, t("Instructor") %></p>
    <p><%= f.text_field :instructor %></p>

    <div class = "field">
		<%= f.label :grade, t("Grade")%>
		<p><%= f.select (:grade),	
	  	 options_for_select([[t('Freshman'), 1], [t('Sophomore'), 2], [t('Junior and Senior'),3], [t('Graduate'),4],[t('Foreign Language'),5],[t('General Knowledge'),6]]) 
		%></p>
    </div>

    <p><%= f.label :description, t("Description") %></p>
    <p><%= f.text_area :description %></p>

    <%= f.submit t("Create") %>
<% end %>

<p><%= button_to t('Back to Course Index'), { :controller => 'courses', :action => 'index'}, :method => 'get' %></p>

app/views/courses/show.html.erb
<p>
<%= link_to t('Back to Home'), root_url, :class => "btn btn-info" %>
<%= link_to t('Back to Course Index'), courses_path, :class => "btn btn-info" %>
</p>

<h1><%= @course.name %></h1>
<table style="word-break:break-all" class="table table-bordered">
<tr>
<td align=center width="33%"> <strong><%= t("Instructor") %></strong></td>  
<td align=center width="33%"> <strong><%= t("Grade") %></strong></td>       
<td align=center width="33%"> <strong><%= t("Average Rating") %></strong></td> 
</tr>
<tr>
<td align="center" width="33%"><%= @course.instructor %></td>
<td align="center" width="33%"><%= t(@grade) %></td>
<td align="center" width="33%"><%= format("%.2f",@average_rate).to_f   %></td>
<tr><td align="center" COLSPAN=3> <strong><%= t("Description") %></strong></td></tr> 
<tr><td align="center" COLSPAN=3> <%= simple_format(@course.description) %></td></tr> 
</table>
<p>
<%= link_to t('Feedbacks'), course_feedbacks_path(@course), :class => "btn btn-primary", :style => 'width: 33%' %>
<%= link_to t('Pastexams'), course_pastexams_path(@course), :class => "btn btn-primary", :style => 'width: 33%'  %>
</p>

app/views/home/index.html.erb
<% if user_signed_in? %>	
	<p><%= link_to image_tag('course.png',width:'49%'), courses_path %>
           <%= link_to image_tag('contact.jpg',width:'49%'), root_url %>
	 
	 <li><%= link_to 'Camp activities', camp_activities_url %> </li>
	 <li><%= link_to 'Camp workers', camp_workers_url %> </li>
	 
	</p>

<% end %>



<!--
	<div class="slideshow">
    	<%= image_tag('songjoe_2013.jpg',width:'49%')%>
    	<%= image_tag('eecscamp_2014_lightball.jpg',width:'49%')%>
    	<%= image_tag('songjoe_2014.jpg',width:'49%')%>
    	<%= image_tag('eecscamp_2015_fireball.jpg',width:'49%')%>
   		<%= image_tag('songjoe_2015.jpg',width:'49%')%>
	</div>
	<p><%= link_to image_tag('course.png',width:'49%'), courses_path %>
           <%= link_to image_tag('contact.jpg',width:'49%'), root_url %>
	 
	 <li><%= link_to 'Camp activities', camp_activities_url %> </li>
	 <li><%= link_to 'Camp workers', camp_workers_url %> </li>
	 
	</p>


-->